# These are supported funding model platforms

# github: [antriksh123] -- You have not applied for a Github Sponsors account yet. Hide this line until you get an acount activated.

custom: ['https://www.buymeacoffee.com/antarikshyum']
